# Credits to jeanconn for the package https://binstar.org/jeanconn/fftw
package:
    name: libxmlsec1
    version: "1.2.24"

source:
    fn: xmlsec1-1.2.24.tar.gz
    url: http://www.aleksey.com/xmlsec/download/xmlsec1-1.2.24.tar.gz
    md5: 2f4944356b69ea14c18814d9248fbbd8

requirements:
    build:
        - libxml2 >=2.9
        - libgcrypt
        - openssl
        - libiconv=1.15
        - libgpg-error
    run:
        - libxml2 >=2.9
        - libgcrypt
        - openssl
        - libiconv
        - libgpg-error

# Note: tests are run when building the package, they are not accessible
# in the installed package.

about:
    home: https://www.aleksey.com/xmlsec/
    license: MIT
    summary: 'XML Security Library'
