{% set name = "xmlsec" %}
{% set version = "1.3.3" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "e573c0172174973223d874ffd158ecd4e0faa761015474385289a6468dd29ed6" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - pkgconfig
    - lxml >=3.0
    - libxmlsec1 >=1.2.0
  run:
    - python
    - pkgconfig
    - lxml >=3.0
    - libxmlsec1 >=1.2.0

test:
  imports:
    - xmlsec

about:
  home: https://github.com/mehcode/python-xmlsec
  license: MIT License
  license_family: MIT
  license_file: ''
  summary: Python bindings for the XML Security Library
  description: ''
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers:
    - mhworth
